Repository WildCodeSchool-2024-09/JS-RemoteFR-Crew404-P2-TravelUp, pull requests merged in 2024-11, with the labels that each got.

#3 Questions js
  client/src/App.tsx
  client/src/components/QuestionsForm.tsx
  client/src/components/questions.json
Labels: CONFLICTS

#9 Quizz_ok
  client/public/img/beach.png
  client/public/img/budget-high.png
  client/public/img/budget-low.png
  client/public/img/budget-medium.png
  client/public/img/city.png
  client/public/img/climate-cold.png
  client/public/img/climate-temperate.png
  client/public/img/climate-warm.png
  client/public/img/countryside.png
  client/public/img/culinary.png
  client/public/img/family.png
  client/public/img/friends.png
  client/public/img/hiking.png
  client/public/img/mountain.png
  client/public/img/party.png
  client/public/img/relax.png
  client/public/img/shopping.png
  client/public/img/solo.png
  client/public/img/tiep.png
  client/public/img/touring.png
  client/public/img/week.png
  client/public/img/weekend.png
  client/public/img/weeks.png
  client/src/App.tsx
  client/src/components/Checkbox.tsx
  client/src/components/QuestionsForm.css
  client/src/components/QuestionsForm.tsx
  client/src/components/checkbox.css
  client/src/components/questions.json
Labels: CHANGE_REQUESTED

#17 Adding some changes/fashion to the NavBar and fixing Footer
  client/src/components/Footer.css
  client/src/components/NavBar.css
  client/src/pages/Contact.css
  client/src/pages/Contact.tsx
Labels: REVIEWD

#22 Adding some element on const countries in Contact, fixing Map and cha…
  client/src/assets/world.svg
  client/src/components/Map.css
  client/src/components/Map.tsx
  client/src/main.tsx
  client/src/pages/Contact.css
  client/src/pages/Contact.tsx
  client/src/pages/Home.css
  client/src/pages/Home.tsx
  client/src/pages/QuestionsForm.css
  client/src/pages/QuestionsForm.tsx
Labels: CONFLICTS

#24 Adding the NotFound page wich display the 404 error and his mechanic …
  client/src/App.css
  client/src/App.tsx
  client/src/BackgroundStyles.css
  client/src/components/NavBar.css
  client/src/components/WorldMap.css
  client/src/components/WorldMap.tsx
  client/src/main.tsx
  client/src/pages/Contact.css
  client/src/pages/Home.css
  client/src/pages/Home.tsx
  client/src/pages/NotFound.css
  client/src/pages/NotFound.tsx
  client/src/pages/QuestionsForm.tsx
Labels: CONFLICTS_RESOLVED

#26 modication du border du titre à propos
  client/src/pages/About.css
Labels: REVIEWD

#27 Accessibilité
  client/src/components/Footer.tsx
  client/src/components/NavBar.css
  client/src/components/NavBar.tsx
  client/src/main.tsx
  client/src/pages/About.css
  client/src/pages/Contact.css
  client/src/pages/Contact.tsx
  client/src/pages/Home.css
  client/src/pages/Home.tsx
  client/src/pages/NotFound.css
  client/src/pages/NotFound.tsx
  client/src/pages/airplane-svgrepo-com.svg
Labels: REVIEWD

#31 reprise de ma non sauvegarde d'hier menu burger navabr
  client/src/assets/images/menu.png
  client/src/components/NavBar.css
  client/src/components/NavBar.tsx
  client/src/pages/Contact.css
Labels: REVIEWD

#32 Changement logo et ajout icone
  client/index.html
  client/src/assets/images/airplane.png
  client/src/assets/logo.png
Labels: REVIEWD

#33 modification du about et about.css
  client/src/pages/About.css
  client/src/pages/About.tsx
Labels: REVIEWD

#37 New CSS QuestionsFetch
  client/src/pages/QuestionsFetch.css
Labels: REVIEWD

#43 margin du header et modification du background
  client/src/assets/images/aboutimage.jpg
  client/src/pages/About.css
Labels: REVIEWD

#46 Responsiv quiz
  client/src/components/Footer.tsx
  client/src/pages/About.css
  client/src/pages/About.tsx
  client/src/pages/Contact.tsx
  client/src/pages/NotFound.css
  client/src/pages/QuestionsFetch.css
  client/src/pages/QuestionsFetch.tsx
Labels: CONFLICTS_RESOLVED, REVIEWD

#44 Encoooore des modifs
  client/src/pages/About.css
  client/src/pages/About.tsx
  server/src/dataAPI/index.json
Labels: CONFLICTS_RESOLVED

#48 Cette fois c'est la bonne !
  client/src/components/Footer.css
  client/src/pages/About.css
  client/src/pages/About.tsx
  client/src/pages/Home.css
  client/src/pages/QuestionsFetch.css
Labels: REVIEWD
